apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    name: backend-deployment
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: badarabs/backend-ml-project:v1
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql-service 
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: ml-project-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ml-project-secret
              key: MYSQL_PASSWORD
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: FLASK_ENV

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels: 
    name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: backend-cluster-ip

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  MYSQL_DATABASE: db_ml_project
  FLASK_ENV: development