apiVersion: v1
kind: Service
metadata:
  namespace: ml-project
  name: backend-service
  labels: 
    name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005
      name: backend-nodeport-ip
