apiVersion: v1
kind: Service
metadata:
  name: mysql-service-p2
spec:
  type: ClusterIP
  selector:
    app: mysql-p2
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql-cluster-ip-p2
