apiVersion: v1
kind: Service
metadata:
  namespace: ml-project-p2
  name: phpmyadmin-service
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30004
