apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wordpress-service
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: wordpress
  type: NodePort
