apiVersion: v1
kind: Service
metadata:
  namespace: ml-project-2
  name: wordpress-service
  labels:
    name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
      name: wordpress-cluster-ip
