apiVersion: v1
kind: Service
metadata:
  namespace: ml-project-p2
  name: wordpress-service
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: wordpress
  type: NodePort
