apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels: 
    name: backend-service
spec:
  type: ClusterIP
  selector:
    name: backend-deployment
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: backend-cluster-ip
