apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ml-project-2
  name: mysql-deployment-p2
  labels:
    app: mysql-p2
spec:
  selector:
    matchLabels:
      app: mysql-p2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-p2
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-deployment-p2
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-p2
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
