apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap-p2
data:
  MYSQL_DATABASE: db_ml_project_p2
vagrant@uadb:~/ml_project/partie2/secrets$ cat ../deployments/phpmyadmin-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service-p2
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-p2
                  key: password
            - name: PMA_USER
              value: "root"
            - name: PMA_PASSWORD
              value: "toor"
