apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: phpmyadmin-configmap
                  key: HOST
            - name: PMA_PORT
              valueFrom:
                configMapKeyRef:
                  name: phpmyadmin-configmap
                  key: PORT
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secret
                  key: PMA_USER
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secret
                  key: PMA_PASSWORD  
