apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ml-project-p2
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service-p2
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-p2
                  key: password
            - name: PMA_USER
              value: "root"
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-p2
                  key: password  
